import {useEffect,useId,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,CalendarDays,ChartNoAxesCombined,CircleHelp,LoaderCircle,ShieldCheck,TrendingUp} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import './history.css';

type Row=Record<string,any>;
type Props={qs:string;version:number;compact?:boolean;onOpen?:()=>void;onRange?:(start:string,end:string)=>void;onCompany?:(ruc:string)=>void};
const n=(v:any,d=0)=>v==null?'—':new Intl.NumberFormat('es-PE',{maximumFractionDigits:d,minimumFractionDigits:d}).format(Number(v));
const usd=(v:any)=>v==null?'—':'USD '+n(v);
const d=(v:any)=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'}):'—';
const short=(v:any)=>v==null?'—':new Intl.NumberFormat('es-PE',{notation:'compact',maximumFractionDigits:1}).format(Number(v));
const percent=(v:any)=>v==null?'Sin base comparable':(Number(v)>0?'+':'')+n(v,1)+'%';
const statusLabel:Row={backed:'Base semanal cargada',partial:'Cobertura parcial',missing:'Sin base cargada'};
const metricInfo:Row={fob_usd:{label:'FOB declarado',unit:'USD',format:usd},tonnes:{label:'Volumen',unit:'t',format:(v:any)=>n(v,1)+' t'},usd_kg:{label:'Precio ponderado',unit:'FOB USD/kg',format:(v:any)=>n(v,3)+' USD/kg'},operations:{label:'Operaciones',unit:'declaraciones',format:(v:any)=>n(v)},observed_cumulative_fob:{label:'FOB acumulado observado',unit:'USD',format:usd}};
function useAnalytics(path:string,version:number){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch('/api/analytics?'+path,{signal:abort.signal,headers:{'X-Radar-Token':localStorage.getItem('radar-token')||''}}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:'No se pudo consultar el histórico');return body}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[path,version]);return {data,error,loading}}

function Extras({m}:{m:Row}){const cards=[
 ['Precio mediano',n(m.median_usd_kg,3)+' USD/kg','Mediana por serie; no ponderada'],
 ['Rango central de precios',n(m.p25_usd_kg,3)+' – '+n(m.p75_usd_kg,3),'P25–P75 · FOB USD/kg de series'],
 ['Ticket por operación',usd(m.ticket_usd),'FOB conocido / declaraciones'],
 ['Volumen por operación',n(m.tonnes_per_operation,2)+' t','Peso conocido / declaraciones'],
 ['Concentración top 5',m.top5_share_percent==null?'—':n(m.top5_share_percent,1)+'%','FOB de empresas con RUC identificado'],
 ['Importadores recurrentes',n(m.repeat_importers),'Con 2 o más declaraciones en el período'],
 ['Primeras observaciones',n(m.first_observed_importers),'RUC sin historial anterior en este filtro'],
 ['Orígenes activos',n(m.origins),'Países de origen identificados']
 ];return <div className="insight-grid">{cards.map(([label,value,note])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>}

export default function History({qs,version,compact=false,onOpen,onRange,onCompany}:Props){
 const [grain,setGrain]=useState('week'),[metric,setMetric]=useState('fob_usd'),[compareMode,setCompareMode]=useState('previous'),[compareStart,setCompareStart]=useState(''),[compareEnd,setCompareEnd]=useState(''),[exportError,setExportError]=useState('');
 const query=new URLSearchParams(qs);query.set('grain',grain);
 if(compareMode==='custom'&&compareStart&&compareEnd){query.set('compare_start',compareStart);query.set('compare_end',compareEnd)}
 const {data,error,loading}=useAnalytics(query.toString(),version);
 const current=data?.current,previous=data?.previous,m=data?.metrics;
 const customPending=compareMode==='custom'&&(!compareStart||!compareEnd);
 const eligible=data?.comparison?.eligible&&!customPending;
 const chartId=useId().replace(/:/g,'');
 const info=metricInfo[metric];
 async function exportHistory(){setExportError('');try{const r=await fetch('/api/analytics/export?'+query.toString(),{headers:{'X-Radar-Token':localStorage.getItem('radar-token')||''}});if(!r.ok)throw new Error('No se pudo exportar el histórico');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='radar-historico-'+grain+'.csv';a.click();URL.revokeObjectURL(url)}catch(e:any){setExportError(e.message)}}
 function range(weeks:number){const end=data.meta.latest_base_end||data.meta.available_end;const start=new Date(end+'T12:00:00');start.setDate(start.getDate()-weeks*7+1);onRange?.(start.toISOString().slice(0,10),end)}
 if(error)return <div className="error">Histórico: {error}</div>;
 if(!data)return <div className="loading"><LoaderCircle className="spin" size={20}/> Preparando análisis histórico…</div>;
 if(!m)return <section className="panel empty"><ChartNoAxesCombined size={32}/><h3>El histórico comienza con una carga</h3><p>Descarga las bases oficiales para habilitar las métricas.</p></section>;
 if(compact)return <section className="panel analytics-compact"><div className="panel-heading"><div><h2><TrendingUp size={17}/> Métricas del período reciente</h2><p>{d(current.start)} — {d(current.end)} · {current.coverage.days} días</p></div>{onOpen&&<button className="text-btn" onClick={onOpen}>Abrir histórico <ArrowUpRight size={15}/></button>}</div><div className="compact-insights">{[['Precio ponderado',n(m.usd_kg,3)+' USD/kg','usd_kg'],['Ticket por operación',usd(m.ticket_usd),'ticket_usd'],['Importadores recurrentes',n(m.repeat_importers),''],['Concentración top 5',n(m.top5_share_percent,1)+'%','']].map(([label,value,key])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{key?(eligible?percent(data.comparison.deltas[key])+' vs. período anterior':'Comparación sin cobertura suficiente'):(key===''&&label.includes('recurrentes')?'2 o más declaraciones':'Sobre FOB con RUC identificado')}</small></div>)}</div></section>;
 const points=data.timeline.map((r:Row)=>({...r,full:r.status==='backed'?r[metric]:null,partial:r.status==='partial'&&r.series?r[metric]:null}));
 return <div className={'history-view '+(loading?'refreshing':'')}>
 <div className="history-intro"><div><span className="eyebrow">EVOLUCIÓN Y COMPORTAMIENTO</span><h2>Una perspectiva más amplia del mercado</h2><p>{data.meta.windows.length} ventanas semanales cargadas · desde {d(data.meta.available_start)}</p></div><div className="history-presets"><button onClick={()=>range(4)}>Últimas 4 semanas</button><button onClick={()=>range(8)}>Últimas 8 semanas</button><button onClick={()=>onRange?.('','')}>Todo el histórico</button></div></div>
 <section className="period-comparison panel"><div className="comparison-controls"><div><CalendarDays size={18}/><div><h3>Período analizado</h3><strong>{d(current.start)} — {d(current.end)}</strong><small>{current.coverage.days} días · {current.coverage.backed_days} con base cargada</small></div></div><div className="comparison-versus">vs.</div><div><label>Comparar con<select aria-label="Modo de comparación" value={compareMode} onChange={e=>setCompareMode(e.target.value)}><option value="previous">Período anterior de igual duración</option><option value="custom">Elegir otro período</option></select></label>{compareMode==='previous'?<small>{d(previous.start)} — {d(previous.end)}</small>:<div className="custom-dates"><input aria-label="Inicio del período comparado" type="date" value={compareStart} onChange={e=>setCompareStart(e.target.value)}/><span>—</span><input aria-label="Fin del período comparado" type="date" value={compareEnd} onChange={e=>setCompareEnd(e.target.value)}/></div>}</div><span className={'badge '+(eligible?'green':'amber')}>{eligible?'Ventanas respaldadas':'Comparación limitada'}</span></div>
 <div className="history-kpis">{[['fob_usd','Valor FOB',usd],['tonnes','Volumen',(v:any)=>n(v,1)+' t'],['operations','Operaciones',(v:any)=>n(v)],['importers','Importadores',(v:any)=>n(v)]].map(([key,label,fmt]:any)=><article key={key}><span>{label}</span><strong>{fmt(current.metrics[key])}</strong><div className="delta" data-testid={'delta-'+key}>{eligible?percent(data.comparison.deltas[key]):'Sin comparación válida'}</div><small>Anterior: {fmt(previous.metrics[key])}</small></article>)}</div>
 {!eligible&&<div className="comparison-warning"><CircleHelp size={14}/>{customPending?'Completa ambas fechas para comparar.':data.comparison.reasons.join(' · ')}. No se calcula una variación porcentual.</div>}
 </section>
 <div className="history-chart-layout"><section className="panel history-chart-panel"><div className="panel-heading"><div><h2>Histórico de importaciones</h2><p>{d(data.meta.available_start)} — {d(data.meta.available_end)} disponibles · filtros aplicados</p></div><div className="grain-switch" role="group" aria-label="Agrupación histórica">{[['day','Diario'],['week','Semanal'],['month','Mensual']].map(([key,label])=><button key={key} aria-pressed={grain===key} onClick={()=>setGrain(key)}>{label}</button>)}</div></div><div className="history-chart-toolbar"><select aria-label="Métrica del gráfico" value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(metricInfo).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select><div><span className="chart-key backed"/> Base cargada <span className="chart-key partial"/> Observación parcial</div></div>
 <div className="history-main-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:18,right:24,left:8,bottom:8}}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e8edf1"/><XAxis dataKey="period" minTickGap={36} tickFormatter={v=>new Date(v+'T12:00:00').toLocaleDateString('es-PE',{day:grain==='month'?undefined:'2-digit',month:'short'})} tick={{fontSize:10,fill:'#8494a7'}} axisLine={false} tickLine={false}/><YAxis width={65} tickFormatter={v=>metric==='usd_kg'?n(v,2):short(v)} tick={{fontSize:10,fill:'#8494a7'}} axisLine={false} tickLine={false}/><Tooltip content={({active,payload})=>{if(!active||!payload?.length)return null;const r=payload[0].payload;return <div className="history-tooltip"><b>{d(r.selection_start)} — {d(r.selection_end)}</b><strong>{info.format(r[metric])}</strong><span>{statusLabel[r.status]} · {r.coverage.backed_days}/{r.coverage.days} días</span></div>}}/><Line id={chartId} dataKey="full" name={info.label} type="linear" stroke="#258b7b" strokeWidth={2.5} dot={points.length<40?{r:3,fill:'#fff',strokeWidth:2}:false} connectNulls={false} isAnimationActive={false}/><Line dataKey="partial" name="Observación parcial" stroke="#c49a51" strokeWidth={0} dot={{r:5,fill:'#e2bb76',stroke:'#fff',strokeWidth:2}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="history-chart-caption"><ShieldCheck size={14}/><span>Los vacíos no se convierten en cero. Los puntos ámbar indican ventanas parciales y no se conectan como si fueran caídas del mercado.</span></div></section>
 <section className="panel metric-quality"><div className="panel-heading"><div><h2>Calidad de las métricas</h2><p>Período analizado</p></div><ShieldCheck size={18}/></div>{[['Precio calculable',m.priced_percent,`${n(m.priced_series)} de ${n(m.series)} series con FOB/kg`],['Peso verificable',m.weighed_percent,`${n(m.weighed_series)} de ${n(m.series)} series con kg`],['Clasificación por revisar',m.review_percent,`${n(m.review_series)} series pendientes`]].map(([label,value,note])=><div className="quality-bar" key={label}><div><span>{label}</span><b>{value==null?'—':n(value,1)+'%'}</b></div><div className="quality-track"><i style={{width:Math.min(100,Number(value||0))+'%'}}/></div><small>{note}</small></div>)}<div className="history-mini-facts"><span><b>{n(m.active_days)}</b> días con operaciones</span><span><b>{n(m.returning_importers)}</b> RUC ya observados antes</span><span><b>{n(m.suppliers)}</b> proveedores identificados</span></div></section></div>
 <Extras m={m}/>
 <div className="notice"><CircleHelp size={15}/><span>{data.meta.price_note} «Primera observación» significa que no hay registros anteriores en la cobertura y filtro seleccionados; no acredita que una empresa sea nueva en el mercado.</span></div>
 <section className="panel"><div className="panel-heading"><div><h2>Empresas del período</h2><p>Participación en FOB con RUC identificado · hasta 20 empresas</p></div><BuildingLegend/></div><div className="table-scroll"><table><thead><tr><th>Empresa / RUC</th><th className="numeric">FOB actual</th><th className="numeric">FOB anterior</th><th className="numeric">Variación</th><th className="numeric">Participación</th><th>Historial observado</th></tr></thead><tbody>{data.movers.map((r:Row)=><tr key={r.ruc}><td><button className="company-link" onClick={()=>onCompany?.(r.ruc)}>{r.name||r.ruc}</button><small>{r.ruc}</small></td><td className="numeric">{usd(r.fob_usd)}</td><td className="numeric">{usd(r.previous_fob_usd)}</td><td className="numeric">{eligible?percent(r.change_percent):'—'}</td><td className="numeric">{n(r.share_percent,1)}%</td><td><span className={'badge '+(r.first_observed?'amber':'green')}>{r.first_observed?'Primera observación':'Ya observado'}</span></td></tr>)}</tbody></table>{!data.movers.length&&<div className="empty">No hay empresas identificadas en este período.</div>}</div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Tabla histórica</h2><p>Selecciona un período para aplicar sus fechas a todos los filtros.</p></div><button className="btn secondary" onClick={exportHistory}><ArrowDownToLine size={15}/> Exportar histórico</button></div>{exportError&&<div className="error">{exportError}</div>}<div className="table-scroll history-table"><table><thead><tr><th>Período</th><th>Cobertura</th><th className="numeric">FOB USD</th><th className="numeric">Toneladas</th><th className="numeric">Operaciones</th><th className="numeric">Importadores</th><th className="numeric">FOB USD/kg</th><th className="numeric">Δ FOB anterior</th></tr></thead><tbody>{data.timeline.map((r:Row)=><tr key={r.period}><td><button className="text-btn" onClick={()=>onRange?.(r.selection_start,r.selection_end)}>{d(r.selection_start)}<ArrowUpRight size={12}/></button><small>hasta {d(r.selection_end)}</small></td><td><span className={'badge '+(r.status==='backed'?'green':'amber')}>{statusLabel[r.status]}</span><small>{r.coverage.backed_days}/{r.coverage.days} días respaldados</small></td><td className="numeric">{n(r.fob_usd)}</td><td className="numeric">{n(r.tonnes,1)}</td><td className="numeric">{n(r.operations)}</td><td className="numeric">{n(r.importers)}</td><td className="numeric">{n(r.usd_kg,3)}</td><td className="numeric">{r.fob_change_percent==null?'—':percent(r.fob_change_percent)}</td></tr>)}</tbody></table></div></section>
 <div className="notice"><CircleHelp size={15}/><span>{data.meta.coverage_note} Todas las fechas corresponden a numeración de declaraciones, no a llegada física.</span></div>
 </div>
}
function BuildingLegend(){return <span className="badge"><ChartNoAxesCombined size={12}/> Misma selección de productos</span>}
